apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: octank
  annotations:
    service.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 8080